name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - uses: actions/upload-artifact@v3
      with:
          name: debug-build
          path: /home/runner/work/video-web-page-generator/video-web-page-generator/target/debug/
          if-no-files-found: error
    
